### ISSUE TITLE
why need more gpu memory rtx30xx than gtx?

### ISSUE THREAD

**Issue by SinDongHwan** [NVIDIA/tensorflow#23] opened 2021-05-18 06:04 UTC
I want to know reasons.

[environment]

    pc_1 : gtx 1080ti(11G), cuda-10, tensorflow-gpu==1.13
    pc_2 : rtx 2080ti(11G), cuda-10, tensorflow-gpu==1.15
    pc_3 : rtx 2080ti(11G), cuda-11.0, tensorflow-gpu==1.15
    pc_4 : rtx 3080(10G), cuda-11.1, nvidia-tensorflow==r1.15.4-20.11

I’ve loaded a weight file using memory fraction 1.5GB on pc_1~pc_3. I tested that load same weight file using memory fraction 1.5GB on pc_4 yesterday, but couldn’t load. however, I could load it using memory fraction about 5.7GB on pc_4.

although same weight file, why require more gpu memory?
I couldn’t find solutions anywhere. I guess rtx 30xx serise or nvidia-tensorflow is the reason.

**Comment by nluehr** [comment] 2021-05-18 15:23
What error do you see if the GPU memory fraction is too small?

If you enable allow_growth in TF what is the amount of memory used by the TF process on each system?

**Comment by SinDongHwan** [comment] 2021-05-18 17:20
What error do you see if the GPU memory fraction is too small?
 -> i saw OOM error message, when set memory fraction as under 5.7GB on pc_4 environment.

If you enable allow_growth in TF what is the amount of memory used by the TF process on each system?
 -> I've not tested yet. i'm trying it soon.

**Comment by rahman-mdatiqur** [comment] 2021-05-30 15:08
Hello @SinDongHwan and @nluehr ,

I can confirm that I am seeing the same behavior. In my case, my model takes around 11Gigs on Titan Xp with tensorflow-gpu==1.12 while taking around 18 Gigs on RTX 3090  with nvidia-tensorflow==1.15.4+nv20.11 !! In both of the cases, I have allow_growth enabled in tf.

Can you guys please advise what might be the issue?

**Comment by SinDongHwan** [comment] 2021-05-30 16:36
Hi, @rahman-mdatiqur.

I couldn't find problem solutions anywhere. so i will try to convert tf1 codes to tf2 codes using tf.compat.v1 in my programs.
if you  find solutions, please share that.

**Comment by rahman-mdatiqur** [comment] 2021-05-30 18:32
Hello @SinDongHwan ,

I guess, I have to follow the same route. The only problem is my tf1 code is too involved to upgrade to tf2.

**Comment by SinDongHwan** [comment] 2021-05-30 19:46
Hi @rahman-mdatiqur.
I think so. 
My tf1 code, too. And my code included a keras framework. when convert to tf2, I guess many problems, like support op.

I want to analyze this github codes and compare tensorflow package codes. but i don't have many time.

**Comment by memr5** [comment] 2021-08-23 03:57
Hey @SinDongHwan,

any updates in memory issues? I ma having similar issue when I compare memory usage between 2080ti & 3080. In 3080 models are occupying way more memory than in 2080ti. 

I tried [tensorflow containers](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes) for experiments. I found when using latest containers (Ex 21.07, 21.06 etc) the memory usage is more, while using the older containers (20.11) memory usage is less. (down from 3.5 GB to 1.3GB). 

I am not able to figure out the issue. Please update the this thread if you are able to make any progress in this.

https://forums.developer.nvidia.com/t/new-tensorrt-model-occupying-more-gpu-memory-as-compared-to-older-version/186373

**Comment by SinDongHwan** [comment] 2021-08-23 04:06
Hi, @memr5 

Just in my think, the problem can't solve.
I will use the tensorflow 2 version.

In tensorflow 2 version, we can load models of tf version 1 using tensorflow.compat.v1 api.

**Comment by memr5** [comment] 2021-08-23 04:14
Hi @SinDongHwan, 

But loading the tf1 models using tensorflow.compat.v1 in tf2 will also not solve the gpu-memory problem, right? Because I have observed that loading tf2 model, is also occupying more memory.

**Comment by SinDongHwan** [comment] 2021-08-23 04:25
Hi, @memr5.

I solved the problem using tf2. but gpu memory is used a little bit more than pip tf1.

If you use tf2, you don't need to this repository.
You can use tf2 that installed "pip install tensorflow-gpu==2.x.x".

**Comment by memr5** [comment] 2021-08-23 04:39
Hey @SinDongHwan,

I am using tf2. But what I am trying to say that the memory issue is still there for me!

**Comment by DEKHTIARJonathan** [comment] 2021-08-23 04:45
Let's clear out a few things out of the way:

1. It is absolutely normal that two different GPUs (even more from different generations) have vastly different memory consumption. They use/load different (SW/HW) features and kernels, you can't expect them to be working the same.

2. Comparing TF1 and TF2 memory consumption makes no sense. TF1 has not been updated for 2 years now, TF2 behaves vastly different in countless areas. On many regards, they should now be considered different frameworks.

3. Upgrading the CUDA stack (CUDA, cuDNN, cuBLAS, etc.) will have an impact on memory consumption. If you upgrade, you may load heavier (and faster) kernels, which takes more GPU memory, again it's perfectly normal.

------

This thread is a non-issue and will never be fixed. It's like complaining that two different cars have different gas mileage ... Different GPUs, especially from different generations, will lead to different memory usage. It should not be a 100% memory bump though it can vary (upward mostly) with each generation.

I hope that gives an explanation to the different messages in this thread. 
@SinDongHwan if you have no more questions, please close the issue

**Comment by memr5** [comment] 2021-08-23 04:51
Hey @DEKHTIARJonathan,

Thanks for the quick response.

If this is the case, then can you tell me why going from [21.07 Tensorflow-NGC](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_21-07.html#rel_21-07) to [20.11 Tensorflow-NGC](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_20.11.html#rel_20.11) decreased the gpu-memory usage from **3.5GB to 1.3GB** for the same GPU?

We tested with both TF1.15 & TF2.5 in [20.11 Tensorflow-NGC](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_20.11.html#rel_20.11), both are occupying same gpu-memory. So we can rule out the TF version issue in this case.

I just wanted to know that if this could be because of new CUDA or cuDNN libraries.

Thanks!

**Comment by DEKHTIARJonathan** [comment] 2021-08-23 04:53
> If this is the case, then can you tell me why going from 21.07 Tensorflow-NGC to 20.11 Tensorflow-NGC decreased the gpu-memory usage from 3.5GB to 1.3GB for the same GPU?

See point 3)

> I just want to know that if this could be because of new CUDA or cuDNN libraries.
- If TF1: Yes, most likely. The memory increase should come with a speed increase.
- If TF2: Could be TF or the CUDA stack or combination of both

As for a note:
- 21.07 => CUDA 11
- 20.11 => CUDA 10

They are totally different containers.

**Comment by memr5** [comment] 2021-08-23 04:58
Thanks,

> As for a note:
> 
> * 21.07 => CUDA 11
> * 20.11 => CUDA 10

Just want to correct that 20.11 (11.1) is also cuda 11 like 21.07 (11.4)

**Comment by DEKHTIARJonathan** [comment] 2021-08-23 05:00
Oh my bad, I thought it was introduced later. It doesn't change the point. Between 11.1 and 11.4 there has been a lot of changes.
Honestly, if you don't see a speedup, and the memory consumption go up. Feel free to use 20.11, especially if you're using TF1 since the codebase is always always the same for each single release for virtually 2 years now.

**Comment by memr5** [comment] 2021-08-23 06:04
Hey @DEKHTIARJonathan,

As you said 100% memory bump is not expected.
But here we are seeing:

Tensorflow Containers: 
* 19.01: ~700 MB (2080 ti & TF 1.14)
* 20.11: ~1.3 GB (3080 & TF1.15 | TF2.3) | 2x Jump (Understandable)
* 21.07: ~3.5 GB (3080 & TF1.15 | TF2.5) | 5x Jump (Way too much)

It is a big jump! What should we do about this?

**Comment by DEKHTIARJonathan** [comment] 2021-08-23 06:09
>What should we do about this?

Nothing. There's nothing to do about this. Nothing you can do, nothing we will do. It is not "a bug", it's by design (we don't intend to increase mem usage, we add new features & kernels => leads to greater mem usage. That's just the way it is).

You are comparing two different generations of GPUs with 2.5 years of improvements in between. Sorry, it's not gonna happen.
It's totally normal and expected. I'm sure if you compare with the 1080Ti it will be even more: because it doesn't make sense to compare.

There's nothing more to add I'm sorry. You have the reason why it happens. Now you can take an informed decision on which version/container to use.

**Comment by SinDongHwan** [comment] 2021-08-23 07:13
@memr5.
I recommend to use a original tensorflow package(not this repository).
the latest version of tensorflow support over 11.1 of CUDA version.

**Closed as completed** 2021-12-02 20:48 UTC
